##################################################
# Makefile of boot.asm (x=[1,2,3...])
##################################################

SRCBOOT:=boot.asm
BINBOOT:=$(subst .asm,.bin,$(SRCBOOT)) #${SRCBOOT}中的.asm会替换成.bin
SRCLOADER:=loader.asm
BINLOADER:=$(subst .asm,.bin,$(SRCLOADER)) #${SRCLOADER}中的.asm会替换成.bin

.PHONY : everything

everything : $(BINBOOT) $(BINLOADER)
     dd if=boot.bin  of=a.img bs=512 count=1 conv=notrunc
     sudo mount -o loop a.img  /mnt/floppy/
     sudo cp loader.bin /mnt/floopy/ -v
     sudo umount /mnt/floppy/

$(BINBOOT) : $(SRCBOOT)
	nasm $< -o $@ #等价与nasm boot.asm -o boot.bin
$(BINLOADER) : $(SRCLOADER)
	nasm $< -o $@ #等价与nasm loader.asm -o loader.bin


