##################################################
# Makefile
##################################################

SRCBOOT:=foo.asm
BINBOOT:=$(subst .asm,.o,$(SRCBOOT)) 


.PHONY : everything

everything : $(BINBOOT) bar.o foobar

$(BINBOOT) : $(SRCBOOT)
	nasm -f elf32 $< -o $@ 
bar.o : bar.c
	gcc -c -m32  $< -o $@
foobar : foo.o bar.o
	ld  -m elf_i386 foo.o bar.o -o foobar
